[env:seeed_xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SH110X @ ^2.1.10
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    dfrobot/DFRobotDFPlayerMini @ ^1.0.6
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
